services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - "3000"              # host dynamique -> conteneur 3000
    environment:
      - PORT=3000           # conteneur écoute sur 3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=bibli_app
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    depends_on:
      - db
      - mailpit

  client:
    build:
      context: ./client
      target: dev
    ports:
      - "5173"              # host dynamique -> conteneur 5173
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - server

  db:
    image: mysql:8.0
    # pas besoin d'exposer de port en dev si tu utilises phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bibli_app
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080"           # fixe (ou "80" pour dynamique)
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025"         # fixe (ou "8025" pour dynamique)
      - "1025"         # fixe (ou "1025" pour dynamique)

volumes:
  mysql_data:
  server_node_modules:
  client_node_modules:
